spring:
  data:
    mongodb:
      database: loja-produtos

server:
  port: ${PORT:9392}

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

