server:
  port: ${PORT:9023}


eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

zuul:
  prefix: /api
  routes:
    produtos-service: /catalogo/**
    carrinho-service: /loja/**